# Message received on the chat cibled by the /verifafk command.
# Hover confirmation message is a message shown when the mouse is on the Confirmation message.
Confirmations messages:
  - "{prefix} &ePlease click here ton confirm your presence."
  - "{prefix} &ePlease click here ton confirm your presence. (second message)"
Hover confirmation message: "&bClick here to confirm."
Verification message: "{prefix} &aVerification send to &e{player}&a."
Verification offline player: "{prefix} &cThe player {player} is offline."
Player make the confirmation: "{prefix} &e{player} &amake the verification."
Presence confirmed: "{prefix} &aPresence confirmed."

# customisation of the sound played to the verified player.
# All available sounds can be found there : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
Verification sound: "ENTITY_PLAYER_LEVELUP"
Sound volume: 1.0
Sound pitch: 1.0

# Settings of the title shown to the player.
# Durations are on ticks (20 ticks = 1 second)
Verification title: "&cAFK Check!"
Verification subtitle: "&eClick on the message on the chat."
fade_in: 10
stay: 70
fade_out: 20

# Time before player can't click on the verification message (20 ticks = 1 second)
Expiry duration: 600