afk-message: "{prefix} &ePlease click here ton confirm your presence."
tooltip-message: "Click here to confirm."
afk-sound: "ENTITY_PLAYER_LEVELUP"
afk-title: "&cAFK Check!"
afk-subtitle: "&eClick on the message on the chat."
afk-success: "{prefix} &aVerification send to &e{player}&a."
Player_present: "{prefix} &e{player} &amake the verification."
Player_offline: "{prefix} &cThe player {player} is offline."
Player_confirmed: "{prefix} &aPresence confirmed."