name: VerifAFK
version: '${project.version}'
main: be.achent.verifafk.VerifAFK
api-version: '1.20'
commands:
  verifafk:
    description: Main Command
  verifafkconfirm:
    description: Command executed ton confirm
permissions:
  verifafk.*:
    description: Give all permissions
    children:
      verifafk.use: true
      verifafk.reload: true
  verifafk.use:
    description: Permission to use the verification system
    default: op
  verifafk.reload:
    description: Permission for the reload command
    default: op